#spring:
#  datasource:
#    url: jdbc:postgresql://db.animal.shop:5432/animal_prod_db
#    username: ${DB_USERNAME} # 보안을 위해 환경 변수 사용
#    password: ${DB_PASSWORD}
#
#  jpa:
#    hibernate:
#      ddl-auto: validate # 운영 DB 보호를 위해 구조 체크만 수행
#    show-sql: false